.rubocop.yml, app/models/foreman_fog_proxmox/proxmox.rb, app/overrides/compute_resources_vms/form/add_clone_to_new_vm_compute_detail.rb, app/overrides/compute_resources_vms/form/add_from_profile_to_compute_attributes_form.rb, app/overrides/compute_resources_vms/form/add_vm_type_to_networks_form.rb, app/overrides/compute_resources_vms/form/add_vm_type_to_nic_provider_specific_form.rb, app/overrides/compute_resources_vms/form/add_vm_type_to_volumes_edit.rb, app/overrides/compute_resources_vms/form/add_vm_type_to_volumes_new_volume.rb, app/overrides/compute_resources_vms/form/remove_new_vm_from_removable_layout.rb
introduced in pull request #100
=> Fix deface hates frozen string literals

app/views/api/v2/compute_resources/proxmox.json.rabl
Remove unwanted value from API-result.
=> Fix clean API result

app/assets/javascripts/foreman_fog_proxmox/proxmox_compute_resource.js, app/assets/javascripts/foreman_fog_proxmox/proxmox_vm.js, app/assets/javascripts/foreman_fog_proxmox/proxmox_vm_server.js, app/assets/javascripts/foreman_fog_proxmox/proxmox_volume_cloudinit.js, app/helpers/proxmox_form_helper.rb, app/views/compute_resources_vms/form/proxmox/_base.html.erb
As part of this change:
https://github.com/theforeman/foreman/pull/8538
removed the deprecated parts.
=> Remove deprecated jquery ui spinner

README.md, app/helpers/proxmox_compute_resources_helper.rb, app/helpers/proxmox_vm_config_helper.rb, app/helpers/proxmox_vm_volumes_helper.rb, app/models/foreman_fog_proxmox/proxmox.rb, app/models/foreman_fog_proxmox/proxmox_images.rb, app/models/foreman_fog_proxmox/proxmox_pools.rb, app/models/foreman_fog_proxmox/proxmox_version.rb, app/models/foreman_fog_proxmox/proxmox_vm_commands.rb, app/models/foreman_fog_proxmox/proxmox_vm_new.rb, app/models/foreman_fog_proxmox/proxmox_vm_queries.rb, app/models/foreman_fog_proxmox/proxmox_volumes.rb, locale/en/foreman_fog_proxmox.po, locale/foreman_fog_proxmox.pot, locale/fr/foreman_fog_proxmox.po
=> refactor(lang): remove logger statements from translation

app/views/compute_resources_vms/form/proxmox/container/_network.html.erb, app/views/compute_resources_vms/form/proxmox/server/_network.html.erb
=> fix: VLAN Tag is not transmitted to the proxmox api at vm creation

app/helpers/proxmox_vm_cloudinit_helper.rb
=> Fixes adding cloudinit drive to proxmox host

app/models/foreman_fog_proxmox/proxmox_volumes.rb, test/unit/foreman_fog_proxmox/proxmox_vm_commands_server_update_cdrom_test.rb, test/unit/foreman_fog_proxmox/proxmox_vm_commands_server_update_hard_disk_test.rb
=> Fixes Host updation error if LXC Container has only root disk

app/models/foreman_fog_proxmox/proxmox_compute_attributes.rb
=> Fixes mac address change in Proxmox server on editing host

app/views/compute_resources_vms/form/proxmox/_general.html.erb
=> Fixes start_after_create checkbox on compute_profile

app/models/foreman_fog_proxmox/proxmox_images.rb
=> Fixes templates listing while creating image

app/models/foreman_fog_proxmox/proxmox_vm_commands.rb
=> Fixes deletion of foreman host if associated vm doesn't exist in proxmox server

app/models/concerns/fog_extensions/proxmox/server.rb
=> Fixes notification error for power status of lxc container

app/helpers/proxmox_vm_config_helper.rb, app/models/foreman_fog_proxmox/proxmox_images.rb, app/models/foreman_fog_proxmox/proxmox_vm_commands.rb, test/unit/foreman_fog_proxmox/proxmox_images_test.rb, test/unit/foreman_fog_proxmox/proxmox_vm_commands_container_test.rb, test/unit/foreman_fog_proxmox/proxmox_vm_commands_server_create_test.rb
=> Add feature to configure QEMU/KVM servers when cloning

app/helpers/proxmox_vm_config_helper.rb, app/helpers/proxmox_vm_interfaces_helper.rb, test/unit/foreman_fog_proxmox/helpers/proxmox_vm_helper_test.rb
=> Fixes mac address change on editing host

app/models/foreman_fog_proxmox/proxmox_vm_commands.rb
The field storing the proxmox virtual id is called "vmid"
=> Fix exception handling. 

CHANGELOG.md, lib/foreman_fog_proxmox/version.rb
Reverts theforeman/foreman_fog_proxmox#280
=> Revert "chore(master): release 0.14.3"

app/models/foreman_fog_proxmox/proxmox_interfaces.rb
=> fix: DNS issue for host deployment with nic identifier

.github/workflows/ci.yml
draft, as it kills the coverage integration you have :(
=> Rewrite CI using shared GHA action

webpack/components/ProxmoxComputeSelectors.js
=> fix: Add cpu types to qemu server

app/views/templates/provisioning/user_data/proxmox_user_data.erb
See https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html#routes-sequence-of-mapping
=> Fix default route

lib/foreman_fog_proxmox/engine.rb, package.json, webpack/components/ProxmoxServer/components/CDRom.js, webpack/components/ProxmoxServer/components/CPUFlagsModal.js
Needs https://github.com/theforeman/foreman-js/pull/481/ and https://github.com/theforeman/foreman first
Tracker here: https://projects.theforeman.org/issues/37745
=> Update to Patternfly 5
